### PR TITLE
delete oldest images first and stop after minimum_images are reached

### PR DESCRIPTION
**Pull request by svenbs**
Hi @n0madic,

images could be deleted, if they were older then `--days` if on first iteration the current image count was less than --minimum. So you could end up with 0 images. This change will keep images older then `--days` if `--minimum` image count is hit while deleting images.

Also oldest image will be deleted first, as this implements a sort on the "created" information from the registry.

Regards,
Sven

### CODE REVIEW

**Comment by n0madic** [comment]
Thank you for your pull request!

I corrected your PR:
- Removed requests to the server when their results are not required
- You can not delete the elements of the array on which the cycle is running - the index is shifted and some elements are skipped ...

**Comment by n0madic** [comment]
I rolled back the PR because of the problem I found ...
If several tags refer to the same image, then deleting one of the tags makes it impossible to delete the rest, since you can not get the tag digest ...
I left only the verification of the number of images when deleting.

**Comment by svenbs** [comment]
Hi @n0madic,

i dont quite get why rolling back the PR should fix this problem, as you still iterate over all tags. If you hit a tag that is referring the same image as a tag before the same issue should occur.

Or am I getting this wrong?

Regards,
svenbs

**Comment by n0madic** [comment]
Now the tag is simply skipped if its image was not found, and there were no empty tags with "null bytes". While there is no time to understand the problem ..

**Pull request merged**
