### PR TITLE
Adding some new features and fixing bug

### PR DESCRIPTION
**Pull request by iTaybb**
* Adding new options regarding tags matching

          - -mr, --match-regex to enable regex matching
          - -mn, --match-negate to match the opposite of something
          - --clean-latest to enable "latest" tag removal
* better handling of latest tags (refactoring) + better logging
* fix bugs
      - minimum and days arguments couldn't be 0
      - could not ready the conf file when the working directory is different from the config directory
* better README

### CODE REVIEW

**Comment by n0madic** [comment]
LGFM, thanks!

Please correct the help of new arguments - it starts with a small letter (including README)

**Comment by n0madic** [comment]
I hurried with the merge...

I have a case when the latest tag points to another tag which is used to launch images. Your option can remove that tag leaving only the latest ... Therefore, you need to get the current ID of the latest and skip all the images with the same ID.

**Comment by iTaybb** [comment]
I get what you're saying. I'm not sure this is the preferred outcome. Think
of how Linux implements hard links.
You can remove each hard link, but only when all the links are removed, the
actual data is deleted.
I think that might me the same case.
It's up to your decision, thought. If you want to retain the previous
behavior, I'll patch it up

**Comment by n0madic** [comment]
Yes, the data remains, but the tag itself becomes inaccessible, only latest.  And you can not roll back to it when it stops being the latest.  Please return the old conduct.

**Comment by iTaybb** [comment]
I will. Hopefully I'll get to it tomorrow. will send a new pull request
(since that is already merged)

**Pull request merged**
